language: python
python:
  - "3.5"
install:
  - "pip install ."
before_script:
  - "pip install codecov"
after_success:
  - codecov
script:
  - "python setup.py test"
branches:
  only:
    - master
    - develop
