language: python
python:
  - "3.5"
install:
  - "pip install ."
before_script:
  - pip install git+https://github.com/Rostlab/nalaf.git@feature/Experimental
  - python -m nalaf.download_corpora
  - pip install codecov
  - wget http://download.joachims.org/svm_light/current/svm_light.tar.gz -O /tmp/svm_light.tar.gz
  - mkdir svm_light && cd svm_light
  - tar -xvf /tmp/svm_light.tar.gz
  - make
  - export PATH=$PATH:$PWD
after_success:
  - "codecov"
script:
  - "py.test -v"
branches:
  only:
    - master
    - develop
