language: python

python:
  - "3.5"

branches:
  only:
    - master
    - develop

env:
  - SVM_LIGHT=$HOME/svm_light
  - PATH=$PATH:$SVM_LIGHT

cache:
  pip: true
  directories:
    - $SVM_LIGHT

before_install:
  - printenv # Just for debugging purposes
  - pip install git+https://github.com/Rostlab/nalaf.git@feature/Experimental
  - python -m nalaf.download_corpora
  - pip install codecov pytest-cov
  - test -d $SVM_LIGHT && echo "Use cached svm_light" || (wget http://download.joachims.org/svm_light/current/svm_light.tar.gz -O /tmp/svm_light.tar.gz && mkdir $SVM_LIGHT && cd $SVM_LIGHT && tar -xvf /tmp/svm_light.tar.gz && make)
  #- export
  - cd $TRAVIS_BUILD_DIR

install:
  - pip install .

script:
  - py.test -v --cov=./

after_success:
  - codecov
