language: python

python:
  - "3.5"

cache:
  pip: true

install:
  - pip install git+https://github.com/Rostlab/nalaf.git@feature/Experimental
  - python -m nalaf.download_corpora
  - pip install codecov
  - wget http://download.joachims.org/svm_light/current/svm_light.tar.gz -O /tmp/svm_light.tar.gz
  - mkdir svm_light && cd svm_light
  - tar -xvf /tmp/svm_light.tar.gz
  - make
  - export PATH=$PATH:$PWD
  - cd $TRAVIS_BUILD_DIR
  - pip install .

script:
  - py.test -v

after_success:
  - codecov

branches:
  only:
    - master
    - develop
